# Generated by Django 4.1.4 on 2023-01-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_followers_userprofile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayrating',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
