# Generated by Django 4.1.4 on 2023-01-11 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dayrating_likes_comment_dayrating_commnets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='likes',
        ),
    ]
