# Generated by Django 4.1.4 on 2023-01-11 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_dayrating_likes_like_dayrating_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayrating',
            old_name='commnets',
            new_name='comments',
        ),
    ]
