# Generated by Django 4.1.4 on 2023-01-16 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_dayrating_user_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayrating',
            name='likes',
            field=models.ManyToManyField(related_name='rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
